version: '2'
services:
  retrospective-monster-api:
    build:
      context: ../..
      dockerfile: ./bin/development/Dockerfile
    command: yarn start:dev
    volumes:
      - ../..:/usr/app/
    ports:
      - "8080:8080"
    depends_on:
      - localstack
      - redis

  localstack:
    image: "localstack/localstack"
    ports:
      - "4566:4566"

  redis:
    image: "redis:5"
    ports:
      - "6379:6379"
